# config/routes.yaml
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

health-check:
    path: /api/health-check
    controller: App\UI\Http\HealthCheckController


post-users:
    path: /api/users
    methods: POST
    controller: App\UI\Http\CreateUserController

get-users-list:
    path: /api/users
    methods: GET
    controller: App\UI\Http\GetUsersListController

get-user:
    path: /api/users/{id}
    methods: GET
    controller: App\UI\Http\GetUserController
